language: node_js
node_js: 
  - 8.9.4
cache:
  directories:
    - node_modules
install: 
  - npm install
script: 
  - npm run build
# after_success:
#   - cd dist
#   - git init
#   - git config user.name "nooldey"
#   - git config user.email "nooldey@gmail.com"
#   - git add .
#   - git commit -m 'Update pages'
#   - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
