language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  keep-history: true
  local-dir: public/dist
  on:
    branch: master
env:
  global:
  - secure: aV810hBZftMJcbscLYyaJ2hpfmROVt26SqtdenfP7unoOSvpnR4cd5TI2ZGL+K2l6DNjjdqYT649maFYzzsqN8woy/zpf63L0b+CZH01k+/Ago0Xf7tKMuBnbB/vycg6OiwCfHLv9HWti+79SXAmnJO0lNEZ2MX5gAUeOYCQ3WtncPLULA0oychPUu55VcP0UzNlMuH5a0Z98UiQhbrC+fvS9a04MnWhfomB6FcQmEHM8zl8Kkrx7EwS7HEjNKmIAkDIKPfGpvgIqdgW34YkT6DbfmfxS+xgXNTSytrMoGzOpohR/7gPBy1zNQTI8ceGx+EWayKKAMqIYz/EcKzbG+ZbbB5m+jiWSXGTgr9dypgRwG0dAIjni+vXrIve95qfBncb2dGTLHEpwASeqcq7TykTcOGwSP8tN2ax9TZlmTzWy1lRGyim9QKeRJTduqV1b+r1+uK6SxDentY0m1TSdDnypqEPdfLKPzy7gwDuDF2kGWHe8cheLVSKOTaavz/KhkKyxxPvR8eSfaPOSnor898RXEaLqaBiczNQ0iSBmFRxVbRdJSwcJngZ3FEEcLUJbdMfmyjUl8VpTwZ1S60CL/jMg4+LuwLqvvgHNoFqzr6QZW2ncIGCiedO1/e4OK3E4edvt8LQgrIdooGksy0iB9dkGpmsRZfHbeJL7vEOliU=
