language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  keep-history: true
  local-dir: dist
  on:
    branch: master
env:
  global:
    secure: VvTfCegMVpdVLFmvi2nPjGb7gtjE7/jP3D3PCKkyoVmJdvMsI2/gOjZZoffQ+5j0e5pfXkCZgr7C0ixCmiS/omEIgZeCNG8h6hKRmKN7NhDp/t82GbAryyGqzMg59onL2QuEFaa6Kc3LPv8VXZ7i4+pKQEZmd7BjK+/1pZNINOuRILtYpF+q9Tj+p/KHvaE7rL1UQ6rxzvVprW3+TRCQk2Ite0eI4u5750+WC2i4sA0TljFHOVooQiqC53IxNoAORnPOuyX8bbAJS3BlhqvQpXoGxSQzffgHFacTfeL4Rmvi2oPBaLw2gmZYjGrLDH75Tevio0gGhPQSLxCYaQxW0liRmUiNi8FDTZKentaSbXyJvW7DN6Xc0huxBpQXjkgwqqKG3aIlaVMsnWOWukxi4uzJj+bkNMczJ9WkD7dbegfcK1ejOT04ENOAiCMHOsGlHwpyJs9FHDaSvpg+1k2Bj7pcIanB91W98UQLz9+XE6Y6BlOuJ1eGMODS5jKcF1pOok8YYzCPpdQ3HfZgWOnFWk41SDzPBjSgLPYp1XBfJK7WLbGASvAQXX1S06UsSHXIxlYdiW0K2K1yJ9bUlQu6EWCJcac4iniWUvVvmx/Sc3HAwBSFEgxKbj6Pg9ufKn0H4vzTZwTrEh2uGZIi2dbMOZhrWoM2iChJqGfWCSq0S9Y=
